name=GFX_light
version=1.0.0
author=Kamil Sabuev
maintainer=Kamil Sabuev
sentence=Graphics library for displays
paragraph=Minimal graphics library compatible with Adafruit_GFX
category=Display
url=https://github.com/KSabuev/GFX_light
architectures=avr
includes=GFX_light.h